### ISSUE TITLE
Simple way to add user-defined T and q tendencies to radiative-convective model?

### ISSUE THREAD

**Issue by micamus** [brian-rose/climlab#76]
I would like to add user-defined T and q tendencies to the radiative-convective model, in order to simulate the effect of advection. I imagine it would look like a subprocess where I would input the two tendency arrays.
Is there a simple way to do this?

**Comment by brian-rose** [comment]
It's a bit clunky, but you can handle the T tendency with the class
```climlab.process.energy_budget.ExternalEnergySource```
which just lets you set a fixed `heating_rate` dictionary and applies it at each timestep.

The heating rate here in this case is specified in W/m2 for each grid cell.

I don't have anything equivalent for q. Are you using the Emanuel convection scheme with prognostic water vapor?

**Comment by brian-rose** [comment]
This is definitely more complicated than it should be.

Really you just want an instance of `TimeDependentProcess` that just always returns the same (specified) tendencies when its `compute()` method is called.

One way to do this quickly:

Subclass `climlab.process.TimeDependentProcess` and overwrite its `_compute` method to just return the desired dictionary of T and q tendencies.

**Comment by brian-rose** [comment]
This should work:

```
import climlab

class ExternalForcing(climlab.process.TimeDependentProcess):
    def __init__(self,**kwargs):
        super(ExternalForcing, self).__init__(**kwargs)
        self.forcing_tendencies = {}
        for var in self.state:
            self.forcing_tendencies[var] = 0. * self.state[var]

    def _compute(self):
        return self.forcing_tendencies
```

The user can then invoke the subprocess with
```
myforcing = ExternalForcing(state=mystate)
```
and then set the desired tendencies in the dictionary
```
myforcing.forcing_tendencies
```
in units of [state variable unit] per second.

**Comment by micamus** [comment]
Excellent, thanks. Then I suppose you would then simply couple the external forcing to the head process with 
``rce.add_subprocess('advective forcing', myforcing)``

**Comment by brian-rose** [comment]
Exactly! 

Somebody should probably make a PR to add an `ExternalForcing` class like this to the codebase -- with some useful documentation.

**Comment by brian-rose** [comment]
This is now implemented as `climlab.process.ExternalForcing` with #78

**Comment by micamus** [comment]
Hi ! 

I would like to do the same with humidity advection.

Here is the model setup I am using : 

state = climlab.column_state(num_lev=40, num_lat=1, water_depth=5.)
rce = climlab.TimeDependentProcess(state=state)
h2o = climlab.radiation.ManabeWaterVapor(state=state)
convadj = climlab.convection.ConvectiveAdjustment(state=state, adj_lapse_rate='MALR')
abs_vmr = climlab.radiation.radiation.default_absorbers(rce.Tatm)
abs_vmr['CO2']=3e-4
rad = climlab.radiation.CAM3(state=state,specific_humidity=h2o.q, insolation = 180, absorber_vmr = abs_vmr)
Tadv = ExternalForcing(state=state)
Tadv.forcing_tendencies['Tatm']=np.interp(rce.lev,srm.sig_*1000, (dt_adv_inc+dt_diff_ctl)/(24*3600))
rce.add_subprocess('Radiation', rad)
rce.add_subprocess('ConvectiveAdjustment', convadj)
rce.add_subprocess('H2O', h2o)
rce.add_subprocess('Temp advection', Tadv)
rce.integrate_years(3)

I would like to add it the same way using something like:

Qadv = ExternalForcing(specific_humidity=h2o.q)
Qadv.forcing_tendencies['q']=q_tendency_input
rce.add_subprocess('q advection', Qadv)

But this does not work since q is not a state variable. Is there a simple way of doing this?

**Comment by brian-rose** [comment]
It's not clear to me exactly what you want to do here. The `ManabeWaterVapor` process resets the specific humidity at every timestep in order to maintain a prescribed relative humidity profile. In this context, adding another tendency to the specific humidity doesn't make any sense.

How do you actually want specific humidity to be determined at each timestep in your model?

**Comment by micamus** [comment]
Oh, I misunderstood what the `ManabeWaterVapor` process does.

I want to add a humidity tendency in the same way that I added a temperature tendency, as an external forcing. But, since the relative humidity profile is prescribed, I suppose that means the humidity tendency can be translated into a temperature tendency. Does that make sense?

**Comment by brian-rose** [comment]
It doesn't make sense to me, no. It's not clear to me what physical system you are trying to model. 

Either specific humidity is a state variable of the model, subject to competing tendencies from various processes (including an externally imposed tendency using `climlab.process.ExternalForcing`), or it is strictly a diagnostic quantity that can be computed from instantaneous temperatures (which is what `ManabeWaterVapor` does). 

Certainly you could add a temperature tendency in order to increase the specific humidity, but I don't think that's what you want to do, because that would obviously also increase the temperature.

Maybe what you really want is to make changes to the *relative humidity* profile? You can do this by manipulating the `RH_profile` attribute of the `ManabeWaterVapor` class.

On the other hand, if you actually want a model with prognostic water vapor, you could take a look at `climlab.convection.EmanuelConvection` instead of `climlab.convection.ConvectiveAdjustment`. Such a model would also need explicit surface flux processes to provide a source of water vapor through evaporation.

**Comment by micamus** [comment]
I wanted a model with prognostic water vapor, where water vapor is supplied through evaporation and advection. But, I think, in that case, water vapor _is_ a state variable, so adding a tendency term can be done in the same way as for temperature.

I guess I was just confused as to why water vapor was not a state variable in the model I am using, in which it is just a diagnostic variable. Thank you for clearing this up!

**Comment by brian-rose** [comment]
Ok! You can use `climlab.surface.LatentHeatFlux` to handle the surface evaporation. There is code in there to check whether specific humidity is a state variable or not.

I'm working on similar things myself, and I have written a 1D advection solver to handle temperature and moisture tendencies arising from resolved (large-scale) up/downwelling. But that code is not on github just yet.

**Comment by micamus** [comment]
That's exciting. I am trying to model the high latitude climate in a radiative-convective + advection model to understand high latitude lapse rate changes.
